/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jogo_adivinha;

/**
 *
 * @author Gusta
 */
public class jogoAdivinha extends javax.swing.JFrame {

    /**
     * Creates new form jogoAdivinha
     */
    // Armazena o número de tentativas

    public jogoAdivinha() {
    initComponents();
    iniciarJogo(); // Chama o método para iniciar o jogo
}


    private int tentativas; // Armazena o número de tentativas
    private int numeroSecreto; // Armazena o número secreto para o jogador adivinhar

    
    private void iniciarJogo() {

        numeroSecreto = (int) (Math.random() * 1000) + 1; // Gera um novo número entre 1 e 1000
        System.out.println(numeroSecreto);
        tentativas = 0; // Zera o contador de tentativas
        lbTentativas.setText("Tentativas: " + tentativas);
        lbMaiorMenor.setText("");
        lbTextFinal.setText("");
        lbNumeroAcertado.setText("???");
        lbDica.setText("");
        lbUsouDiga.setText("Não usou Dica");
        inputPalpite.setText(""); // Limpa o campo de palpite
        btnDica.setEnabled(true); // Habilita novamente o botão de dica
    
 // Gera um número entre 1 e 1000
        tentativas = 0; // Zera o contador de tentativas
        lbTentativas.setText("Tentativas: " + tentativas); // Atualiza o texto para "Tentativas: 0"
        lbMaiorMenor.setText(""); // Limpa o texto "MAIOR" ou "MENOR"
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel = new javax.swing.JPanel();
        painelSecreto = new javax.swing.JPanel();
        lbNumeroAcertado = new javax.swing.JLabel();
        lbTentativas = new javax.swing.JLabel();
        lbUsouDiga = new javax.swing.JLabel();
        lbMaiorMenor = new javax.swing.JLabel();
        btnPalpite = new javax.swing.JToggleButton();
        inputPalpite = new javax.swing.JTextField();
        btnDica = new javax.swing.JToggleButton();
        lbTextFinal = new javax.swing.JLabel();
        lbDica = new javax.swing.JLabel();
        btnReinicio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        painel.setBackground(new java.awt.Color(0, 0, 0));
        painel.setPreferredSize(new java.awt.Dimension(500, 400));

        lbNumeroAcertado.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbNumeroAcertado.setText("???");

        javax.swing.GroupLayout painelSecretoLayout = new javax.swing.GroupLayout(painelSecreto);
        painelSecreto.setLayout(painelSecretoLayout);
        painelSecretoLayout.setHorizontalGroup(
            painelSecretoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelSecretoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lbNumeroAcertado)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        painelSecretoLayout.setVerticalGroup(
            painelSecretoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelSecretoLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(lbNumeroAcertado, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        lbTentativas.setForeground(new java.awt.Color(0, 204, 0));
        lbTentativas.setText("Tentativas: 0");

        lbUsouDiga.setForeground(new java.awt.Color(0, 204, 0));
        lbUsouDiga.setText("Não usou Dica");

        lbMaiorMenor.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lbMaiorMenor.setForeground(new java.awt.Color(0, 204, 0));
        lbMaiorMenor.setText("MAIOR");

        btnPalpite.setText("Palpitar");
        btnPalpite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPalpiteActionPerformed(evt);
            }
        });

        inputPalpite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPalpiteActionPerformed(evt);
            }
        });

        btnDica.setText("Dica");
        btnDica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDicaActionPerformed(evt);
            }
        });

        lbTextFinal.setForeground(new java.awt.Color(0, 204, 0));
        lbTextFinal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTextFinal.setText(" ");

        lbDica.setForeground(new java.awt.Color(0, 204, 0));

        btnReinicio.setText("Reiniciar");
        btnReinicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReinicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelLayout = new javax.swing.GroupLayout(painel);
        painel.setLayout(painelLayout);
        painelLayout.setHorizontalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTentativas, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbUsouDiga, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(painelSecreto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbMaiorMenor)
                .addGap(108, 108, 108))
            .addGroup(painelLayout.createSequentialGroup()
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelLayout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(btnReinicio))
                    .addGroup(painelLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTextFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(painelLayout.createSequentialGroup()
                                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnPalpite, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                                    .addComponent(btnDica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbDica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(inputPalpite, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE))))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        painelLayout.setVerticalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbTentativas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbUsouDiga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(painelSecreto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)
                        .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPalpite)
                            .addComponent(inputPalpite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(painelLayout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(lbMaiorMenor)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDica)
                    .addComponent(lbDica, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(btnReinicio)
                .addGap(124, 124, 124)
                .addComponent(lbTextFinal)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painel, 594, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputPalpiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPalpiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPalpiteActionPerformed

    private void btnDicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDicaActionPerformed
        if (numeroSecreto % 2 == 0) {
        lbDica.setText("Dica: O número secreto é par!");
    } else {
        lbDica.setText("Dica: O número secreto é ímpar!");
    }
    
    lbUsouDiga.setText("Usou Dica"); // Atualiza a label para indicar que a dica foi usada
    btnDica.setEnabled(false); // Desabilita o botão de dica após usá-lo
    }//GEN-LAST:event_btnDicaActionPerformed

    private void btnPalpiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPalpiteActionPerformed
        // TODO add your handling code here:
        tentativas++; // Aumenta o contador de tentativas
        lbTentativas.setText("Tentativas: " + tentativas); // Atualiza o texto na interface
        
         // Obtém o palpite do usuário
        int palpite;
        try {
            palpite = Integer.parseInt(inputPalpite.getText()); // Converte o texto do input para um inteiro
        } catch (NumberFormatException e) {
            lbTextFinal.setText("Por favor, insira um número válido!");
            return; // Sai do método se o input não for um número
        }
    
        // Verifica se o palpite é igual ao número secreto
        if (palpite == numeroSecreto) {
            lbTextFinal.setText("Parabéns! Você acertou em " + tentativas + " tentativas!");
            lbNumeroAcertado.setText(String.valueOf(numeroSecreto));
        } else if (palpite < numeroSecreto) {
            lbMaiorMenor.setText("MAIOR"); // O número secreto é maior
        } else {
            lbMaiorMenor.setText("MENOR"); // O número secreto é menor
        }
    // Aqui você pode adicionar a lógica para verificar se o palpite está correto
    }//GEN-LAST:event_btnPalpiteActionPerformed

    private void btnReinicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReinicioActionPerformed
        iniciarJogo();
    }//GEN-LAST:event_btnReinicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jogoAdivinha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jogoAdivinha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jogoAdivinha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jogoAdivinha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jogoAdivinha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnDica;
    private javax.swing.JToggleButton btnPalpite;
    private javax.swing.JButton btnReinicio;
    private javax.swing.JTextField inputPalpite;
    private javax.swing.JLabel lbDica;
    private javax.swing.JLabel lbMaiorMenor;
    private javax.swing.JLabel lbNumeroAcertado;
    private javax.swing.JLabel lbTentativas;
    private javax.swing.JLabel lbTextFinal;
    private javax.swing.JLabel lbUsouDiga;
    private javax.swing.JPanel painel;
    private javax.swing.JPanel painelSecreto;
    // End of variables declaration//GEN-END:variables
}
